// Câu đố chữ Hán 字谜 cho trò Đố chữ. BẢN NHÁP — cô duyệt lại (28/09/2026).
// Mỗi câu: [câu đố, đáp án, pinyin, dịch câu đố, lời giải, bộ phận (gợi ý 🧩), độ khó 1–3, nguồn, đáp án phụ cũng tính đúng (nếu có)]
// Nguồn: 'sgk' = danh sách câu đố cho bài 遨游汉字王国 (Ngữ văn lớp 5, bộ 部编), tra qua blog.sina.com.cn/s/blog_13edf17a00102yqj3.html
//        'dg'  = câu đố chữ dân gian, có trong các tuyển tập 字谜大全: maigoo.com/top/433887.html, maigoo.com/top/422797.html;
//                vài câu đối chiếu thêm trên dict.baidu.com, zhidao.baidu.com, iask.sina.com.cn, rqxh.net
//        'td'  = câu đố đơn giản do 吕老师汉语盒 tự đặt (mức Dễ)
// Bộ phận / dịch / lời giải tiếng Việt do 吕老师汉语盒 soạn.
window.CAU_DO_NGUON={sgk:'Câu đố trong bài 遨游汉字王国 (Ngữ văn lớp 5, Trung Quốc)',dg:'Câu đố chữ dân gian Trung Quốc',td:'Câu đố do 吕老师汉语盒 soạn'};
window.CAU_DO=[
["两个月字肩并肩","朋","péng","Hai chữ 月 kề vai nhau","月 + 月 đứng cạnh nhau → 朋 (bạn bè)","月 · 月",1,"dg"],
["两个口","吕","lǚ","Hai cái miệng","口 trên + 口 dưới → 吕 (chữ Lữ trong 吕老师 đó!)","口 · 口",1,"td"],
["三个口","品","pǐn","Ba cái miệng","口 + 口 + 口 → 品","口 · 口 · 口",1,"td"],
["两个人","从","cóng","Hai người","人 + 人 → 从 (từ, theo)","人 · 人",1,"td"],
["三个人","众","zhòng","Ba người","人 + 人 + 人 → 众 (đông người)","人 · 人 · 人",1,"td"],
["两个木","林","lín","Hai cái cây","木 + 木 → 林 (rừng)","木 · 木",1,"td"],
["三个木","森","sēn","Ba cái cây","木 + 木 + 木 → 森 (rừng rậm)","木 · 木 · 木",1,"td"],
["上下串通","卡","kǎ","Trên và dưới thông vào nhau","上 + 下 xuyên qua nhau → 卡 (thẻ)","上 · 下",1,"dg"],
["大口吃小口","回","huí","Miệng lớn nuốt miệng nhỏ","口 to bọc 口 nhỏ → 回 (về)","口 · 口",1,"dg"],
["一女一子","好","hǎo","Một cô gái, một đứa con","女 + 子 → 好 (tốt)","女 · 子",1,"td"],
["一人一口","合","hé","Một người, một cái miệng","人 + 一 + 口 → 合 (hợp)","人 · 一 · 口",1,"dg"],
["山上还有山","出","chū","Trên núi còn có núi","山 + 山 → 出 (ra)","山 · 山",1,"sgk"],
["四四方方一间房，一根木头放中央","困","kùn","Một căn phòng vuông vức, một khúc gỗ đặt ở giữa","囗 + 木 → 困 (buồn ngủ)","囗 · 木",1,"dg"],
["大王头上有一人","全","quán","Trên đầu chữ 王 có một người","人 + 王 → 全 (toàn bộ)","人 · 王",1,"dg"],
["今天心里很高兴","念","niàn","Hôm nay trong lòng rất vui","今 + 心 → 念 (đọc, nhớ)","今 · 心",1,"dg"],
["西边来了个小女孩","要","yào","Từ phía tây có một cô bé đến","西 (覀) + 女 → 要 (muốn)","覀 · 女",1,"dg"],
["有人本领大，能在云上飘","会","huì","Có người tài giỏi, bay lượn trên mây","人 + 云 → 会 (biết, sẽ)","人 · 云",1,"dg"],
["一夜又一夜","多","duō","Đêm này qua đêm khác","夕 (đêm) + 夕 → 多 (nhiều)","夕 · 夕",1,"dg"],
["七十二小时","晶","jīng","72 tiếng đồng hồ","72 giờ = 3 ngày = 三日 → 晶 (lấp lánh)","日 · 日 · 日",2,"sgk"],
["一月一日非今天","明","míng","Một tháng (月), một ngày (日), mà không phải hôm nay","日 + 月 → 明; không phải hôm nay thì là 明天 (ngày mai)","日 · 月",2,"sgk"],
["口里吃个大玉米","国","guó","Trong miệng ăn một bắp ngô (玉米) to","囗 + 玉 → 国 (nước)","囗 · 玉",2,"dg"],
["一个小朋友，进门瞧一瞧，见人就张嘴，等待结果到","问","wèn","Một bạn nhỏ vào cửa ngó nghiêng, gặp ai cũng há miệng, rồi chờ câu trả lời","门 + 口 (há miệng hỏi) → 问 (hỏi)","门 · 口",2,"dg"],
["门里有耳","闻","wén","Trong cửa có cái tai","门 + 耳 → 闻 (nghe, 新闻 tin tức)","门 · 耳",1,"td"],
["门里有日","间","jiān","Trong cửa có mặt trời","门 + 日 → 间 (时间 thời gian)","门 · 日",1,"td"],
["一个人站在大树下","休","xiū","Một người đứng dưới gốc cây to","亻 + 木 → 休 (nghỉ ngơi — đứng dưới gốc cây mà nghỉ!)","亻 · 木",1,"sgk"],
["一加一","王","wáng","Một cộng một","一 + 十 (dấu cộng) + 一 → 王 (không phải 二 đâu nhé!)","一 · 十 · 一",2,"dg"],
["一口吃掉牛尾巴","告","gào","Một cái miệng ăn mất đuôi con bò","牛 mất nét sổ thò xuống (cái đuôi) + 口 → 告 (báo)","牛 · 口",2,"sgk"],
["一人一张口，口下长只手","拿","ná","Một người, một cái miệng, dưới miệng mọc một bàn tay","人 + 一 + 口 = 合, thêm 手 ở dưới → 拿 (cầm)","人 · 一 · 口 · 手",2,"dg"],
["十张口，一颗心","思","sī","Mười cái miệng, một trái tim","十 nằm trong 口 = 田, thêm 心 → 思 (nghĩ)","田 · 心",2,"sgk"],
["二人土上坐","坐","zuò","Hai người ngồi trên đất","人 + 人 + 土 → 坐 (ngồi)","人 · 人 · 土",2,"dg","座"],
["人在草木中","茶","chá","Người ở giữa cỏ và cây","艹 (cỏ) + 人 + 木 → 茶 (trà)","艹 · 人 · 木",2,"dg"],
["半个月亮","胖","pàng","Nửa (半) + mặt trăng (月)","月 + 半 → 胖 (béo)","月 · 半",2,"dg"],
["牛走独木桥","生","shēng","Con bò đi qua cầu độc mộc","牛 + 一 (cây cầu) → 生 (sinh)","牛 · 一",2,"dg"],
["十个哥哥","克","kè","Mười người anh","十 + 兄 (anh) → 克","十 · 兄",2,"dg"],
["自大一点","臭","chòu","Tự cao (自大) thêm một chấm","自 + 大 + 丶 → 臭 (hôi — tự cao là bị chê “hôi” đó 😆)","自 · 大 · 丶",2,"dg"],
["天无它大，人有它大","一","yī","Trời không có nó thì thành 大, người có nó cũng thành 大","天 bỏ 一 = 大, 人 thêm 一 = 大 → 一","天 · 人",2,"dg"],
["一人在内","肉","ròu","Một người ở bên trong chữ 内","内 thêm một 人 nữa → 肉 (thịt)","内 · 人",2,"dg"],
["千里相逢","重","zhòng","Nghìn dặm gặp nhau","千 + 里 → 重 (nặng). Có sách giải là 骤 (马 + 聚), cũng tính đúng","千 · 里",2,"dg","骤"],
["木下有子","李","lǐ","Dưới cây có đứa con","木 + 子 → 李 (họ Lý, 行李 hành lý)","木 · 子",2,"td"],
["人言","信","xìn","Người + lời nói","亻 + 言 → 信 (tin, thư — lời người nói phải giữ chữ tín)","亻 · 言",2,"td"],
["一只狗，两个口，谁遇它谁发愁","哭","kū","Một con chó, hai cái miệng, ai gặp nó cũng buồn rầu","口 + 口 + 犬 (chó) → 哭 (khóc)","口 · 口 · 犬",2,"dg"],
["守门员","闪","shǎn","Người giữ cửa (thủ môn)","门 + 人 (员 = người) → 闪 (lóe, chớp)","门 · 人",2,"dg"],
["一家十一口","吉","jí","Một nhà mười một miệng ăn","十 + 一 = 士, thêm 口 → 吉 (may mắn)","十 · 一 · 口",2,"dg"],
["十日十月","朝","cháo","Mười ngày, mười tháng","十 + 日 + 十 + 月 → 朝 (hướng về, triều)","十 · 日 · 十 · 月",2,"dg"],
["八十八","米","mǐ","Tám mươi tám","八 + 十 + 八 → 米 (gạo, mét)","八 · 十 · 八",2,"dg"],
["一口咬住多半截","名","míng","Một cái miệng ngoạm nửa chữ 多","夕 (nửa của 多) + 口 → 名 (tên)","夕 · 口",2,"dg"],
["人不在其位","立","lì","Người không ở chỗ của mình (位)","位 bỏ 亻 → 立 (đứng)","位 − 亻",2,"dg"],
["一只黑狗，不叫不吼","默","mò","Một con chó đen, không sủa không gầm","黑 + 犬 → 默 (im lặng, 默写 chính tả)","黑 · 犬",2,"sgk"],
["一斗米","料","liào","Một đấu gạo","米 + 斗 → 料 (vật liệu, 饮料 đồ uống)","米 · 斗",2,"dg"],
["千字下面一张口","舌","shé","Dưới chữ 千 có một cái miệng","千 + 口 → 舌 (lưỡi)","千 · 口",2,"td"],
["四张嘴，没头没尾","田","tián","Bốn cái miệng, không đầu không đuôi","4 ô vuông ghép lại, nét sổ giữa không thò lên cũng không thò xuống → 田 (ruộng)","口 · 口 · 口 · 口",2,"dg"],
["四张嘴，有头有尾","申","shēn","Bốn cái miệng, có đầu có đuôi","田 + nét sổ thò cả lên trên lẫn xuống dưới → 申 (申请 xin)","田 · 丨",2,"dg"],
["四张嘴，有头没尾","由","yóu","Bốn cái miệng, có đầu không đuôi","田 + nét sổ chỉ thò lên trên → 由 (自由)","田 · 丨",2,"dg"],
["四张嘴，没头有尾","甲","jiǎ","Bốn cái miệng, không đầu có đuôi","田 + nét sổ chỉ thò xuống dưới → 甲","田 · 丨",2,"dg"],
["三口重叠，莫把品字猜","目","mù","Ba chữ 口 chồng lên nhau, đừng đoán là 品","3 ô vuông xếp chồng thành hình chữ nhật đứng → 目 (mắt)","口 · 口 · 口",2,"dg"],
["三人一日去观景","春","chūn","Ba người, một ngày, đi ngắm cảnh","三 + 人 + 日 → 春 (mùa xuân — mùa đi ngắm cảnh!)","三 · 人 · 日",2,"dg"],
["雨落在横山上","雪","xuě","Mưa rơi trên ngọn núi nằm ngang","雨 + ⺕ (chữ 山 nằm ngang) → 雪 (tuyết)","雨 · ⺕",2,"dg"],
["呆头呆脑，能说会道","口","kǒu","Cái đầu của chữ 呆, lại biết nói biết cãi","Phần đầu của 呆 là 口, mà cái miệng thì biết nói → 口","呆 − 木",2,"dg"],
["说它小，下边大，说它大，上边小","尖","jiān","Bảo nó nhỏ thì dưới lại lớn, bảo nó lớn thì trên lại nhỏ","小 ở trên + 大 ở dưới → 尖 (nhọn)","小 · 大",2,"sgk"],
["点点成金","全","quán","Thêm chấm chấm vào thì thành 金","全 thêm hai chấm → 金, nên đáp án là 全","金 − 丷",2,"dg"],
["舌头舔甘蔗","甜","tián","Cái lưỡi liếm cây mía","舌 + 甘 → 甜 (ngọt)","舌 · 甘",2,"dg"],
["石头砸中皮","破","pò","Hòn đá ném trúng lớp da","石 + 皮 → 破 (vỡ, rách)","石 · 皮",2,"dg"],
["人无信不立","言","yán","Người không có chữ tín thì không đứng vững","信 bỏ 亻 (người) → 言 (lời)","信 − 亻",2,"dg"],
["太阳落到西边","晒","shài","Mặt trời lặn về phía tây","日 + 西 → 晒 (phơi nắng)","日 · 西",2,"dg"],
["十个豆豆入口","喜","xǐ","Mười hạt đậu chui vào miệng","十 + 口 + 豆 xếp chồng → 喜 (喜欢)","十 · 口 · 豆",2,"dg"],
["七人头上长了草","花","huā","Trên đầu 7 người mọc cỏ","艹 + 亻 + 匕 (giống 七) → 花 (hoa)","艹 · 亻 · 匕",2,"dg"],
["告诉非非一件事","靠","kào","Kể (告) cho 非非 một chuyện","告 + 非 → 靠 (dựa)","告 · 非",2,"dg"],
["秀才进门把门关","闭","bì","Anh tú tài vào cửa rồi đóng cửa lại","门 + 才 → 闭 (đóng)","门 · 才",2,"dg"],
["宝贝小口头上开","员","yuán","Chữ 贝, trên đầu mở ra một cái miệng nhỏ","口 + 贝 → 员 (服务员)","口 · 贝",2,"dg"],
["厂里有个白小子","原","yuán","Trong xưởng (厂) có cậu bé họ Bạch (白) nhỏ (小)","厂 + 白 + 小 → 原 (原来)","厂 · 白 · 小",2,"dg"],
["两个先生捡贝壳","赞","zàn","Hai ông tiên sinh nhặt vỏ sò","先 + 先 + 贝 → 赞 (khen)","先 · 先 · 贝",2,"dg"],
["一位先生要走了","选","xuǎn","Một ông tiên sinh sắp đi","先 + 辶 (đi) → 选 (chọn)","先 · 辶",2,"dg"],
["竹子头下每人一口","答","dá","Dưới đầu cây trúc, mỗi người một miệng","⺮ + 人 + 一 + 口 → 答 (回答)","⺮ · 合",2,"dg"],
["走在上面，坐在下面","土","tǔ","Nằm trên chữ 走, nằm dưới chữ 坐","Phần trên của 走 và phần dưới của 坐 đều là 土 (đất)","走 · 坐",2,"dg"],
["头戴一顶帽，忠诚又可靠","实","shí","Chữ 头 đội một chiếc mũ, thật thà đáng tin","宀 (mũ) + 头 → 实 (thật)","宀 · 头",2,"dg"],
["身上有重量，日行才一里","量","liàng","Có ở trong chữ 重量; mặt trời đi được một dặm","日 + 一 + 里 → 量","日 · 一 · 里",2,"dg"],
["行字分两边，双土堆中间","街","jiē","Chữ 行 tách đôi, hai chữ 土 chồng ở giữa","彳 + 圭 (hai 土) + 亍 → 街 (phố)","行 · 土 · 土",2,"dg"],
["种花要除草，一人来一刀","化","huà","Trồng hoa phải nhổ cỏ, một người mang một con dao đến","花 bỏ 艹 còn 化 = 亻 + 匕 (như con dao)","亻 · 匕",2,"dg"],
["这个同学真马虎，同字丢了一小竖","司","sī","Bạn này thật đãng trí, chữ 同 làm rơi một nét sổ nhỏ","同 bỏ nét sổ bên trái → 司 (公司)","同 − 丨",2,"dg"],
["上边正字少一横，下边少字丢一点","步","bù","Trên là chữ 正 thiếu một nét ngang, dưới là chữ 少 mất một chấm","止 + 少 bỏ chấm → 步 (bước, 跑步)","止 · 少",2,"dg"],
["有个同学叫立口，总是摸着耳朵走","部","bù","Có bạn tên 立口, lúc nào cũng sờ tai mà đi","立 + 口 + 阝 (cái tai) → 部","立 · 口 · 阝",2,"dg"],
["刀出鞘","力","lì","Con dao rút khỏi vỏ","Chữ 刀 cho nét ngang thò ra (dao rời vỏ) → 力 (sức)","刀",2,"dg"],
["一箭穿心","必","bì","Một mũi tên xuyên qua tim","心 + nét phẩy xuyên qua → 必 (必须)","心 · 丿",2,"dg"],
["旭日东升","九","jiǔ","Mặt trời mọc lên đằng đông","Chữ 旭 mà mặt trời (日) bay lên mất → còn 九","旭 − 日",2,"dg"],
["太阳的儿子","星","xīng","Con của mặt trời","日 (mặt trời) + 生 (sinh ra) → 星 (ngôi sao)","日 · 生",2,"dg"],
["大丈夫不得出头","天","tiān","Chữ 夫 không được thò đầu lên","夫 bỏ phần nét thò lên trên → 天 (trời)","夫",2,"dg"],
["一边绿，一边红；一边喜雨，一边喜风","秋","qiū","Một bên xanh, một bên đỏ; một bên thích mưa, một bên thích gió","禾 (lúa: xanh, thích mưa) + 火 (lửa: đỏ, thích gió) → 秋 (mùa thu)","禾 · 火",3,"dg"],
["有人不是我，有马飞跑过，有水能养鱼，有土庄稼活","也","yě","Có người thì không phải tôi, có ngựa thì phi nhanh, có nước thì nuôi được cá, có đất thì lúa lên tốt","也 + 亻 = 他 (anh ấy), + 马 = 驰 (phi), + 氵 = 池 (ao), + 土 = 地 (đất)","他 · 驰 · 池 · 地",3,"sgk"],
["一点一横长，口字在中央，大口张着嘴，小口里面藏","高","gāo","Một chấm, một nét ngang dài, chữ 口 ở giữa; miệng lớn há ra, miệng nhỏ trốn bên trong","丶 + 一 + 口 + 冂 + 口 → 高 (cao)","亠 · 口 · 冂 · 口",3,"dg"],
["一个人他姓王，口袋里装着两块糖","金","jīn","Một người họ Vương, trong túi có hai viên kẹo","人 + 王 + hai chấm (hai viên kẹo) → 金 (vàng)","人 · 王 · 丷",3,"dg"],
["东海有条鱼，无头又无尾，更无脊梁骨","日","rì","Biển Đông có con cá, không đầu không đuôi, cũng không có xương sống","鱼 bỏ đầu ⺈ và đuôi 一 còn 田, bỏ nét sổ giữa (xương sống) → 日","鱼 − ⺈ − 一 − 丨",3,"dg"],
["画时圆，写时方，冬时短，夏时长","日","rì","Vẽ thì tròn, viết thì vuông, mùa đông ngắn, mùa hè dài","Mặt trời: vẽ hình tròn, viết chữ vuông, ngày đông ngắn ngày hè dài → 日","mặt trời",3,"sgk"],
["半边生鳞不生角，半边生角不生鳞","鲜","xiān","Một nửa có vảy không có sừng, một nửa có sừng không có vảy","鱼 (cá có vảy) + 羊 (dê có sừng) → 鲜 (tươi, 新鲜)","鱼 · 羊",3,"dg"],
["需要一半，留下一半","雷","léi","Chữ 需 lấy một nửa, chữ 留 để lại một nửa","Nửa trên của 需 là 雨, nửa dưới của 留 là 田 → 雷 (sấm)","雨 · 田",3,"sgk"],
["右边有，左边无；后面有，前面无；哥哥有，弟弟无；周家有，李家无","口","kǒu","Bên phải có, bên trái không; phía sau có, phía trước không; anh có, em không; nhà họ Chu có, nhà họ Lý không","Các chữ 右, 后, 哥, 周 đều có 口; còn 左, 前, 弟, 李 thì không → 口","右 · 后 · 哥 · 周",3,"sgk"],
["时针和分针都指向12","斗","dǒu","Kim giờ và kim phút đều chỉ số 12","12 giờ = 十二点: chữ 十 thêm hai chấm (二点) → 斗","十 · 丶 · 丶",3,"sgk"],
["差一点六斤","兵","bīng","Chữ 六 thiếu một chấm, cộng chữ 斤","六 bỏ chấm còn 一 và 八; 一 ghép với 斤 thành 丘, thêm 八 → 兵 (lính)","斤 · 一 · 八",3,"dg"],
["势如破竹","个","gè","Thế như chẻ tre","Chữ 竹 bị chẻ đôi, mỗi nửa là một chữ 个","竹 ÷ 2",3,"dg"],
["有人偷车","输","shū","Có người lấy trộm xe","偷 mất người (亻) còn 俞, thêm 车 → 输 (thua)","车 · 俞",3,"dg"],
["综合门市","闹","nào","Gộp chữ 门 và chữ 市 lại","门 + 市 → 闹 (热闹 náo nhiệt)","门 · 市",2,"dg"],
["出多一半","岁","suì","Chữ 出 và chữ 多 mỗi chữ lấy một nửa","Nửa của 出 là 山, nửa của 多 là 夕 → 岁 (tuổi)","山 · 夕",3,"dg"],
["身残心不残","息","xī","Thân tàn mà tim không tàn","身 “tàn” chỉ còn 自, 心 còn nguyên → 息 (休息)","自 · 心",3,"dg"],
["传旁人去车来换","转","zhuǎn","Chữ 传: người bên cạnh đi mất, xe đến thay","传 bỏ 亻 thay bằng 车 → 转 (chuyển)","传 − 亻 + 车",3,"dg"],
["心里想着耍赖皮","懒","lǎn","Trong lòng nghĩ chuyện ăn vạ (赖)","忄 + 赖 → 懒 (lười)","忄 · 赖",3,"dg"],
["要一半，扔一半","奶","nǎi","Chữ 要 lấy một nửa, chữ 扔 lấy một nửa","Nửa dưới 要 là 女, nửa phải 扔 là 乃 → 奶 (奶奶)","女 · 乃",3,"dg"],
["很字两人离，木棍左边立","根","gēn","Chữ 很 mất bộ hai người, cây gậy gỗ đứng bên trái","很 bỏ 彳 còn 艮, thêm 木 → 根 (rễ)","木 · 艮",3,"dg"],
["手拿小药丸，愁得直流汗","热","rè","Tay cầm viên thuốc nhỏ, lo quá toát mồ hôi","扌 + 丸 + 灬 (mồ hôi) → 热 (nóng)","扌 · 丸 · 灬",3,"dg"],
["四方来合作，贡献大一点","器","qì","Bốn phương cùng hợp tác, chữ 大 góp thêm một chấm","4 cái 口 + 犬 (大 + 丶) → 器 (机器)","口 · 口 · 口 · 口 · 犬",3,"dg"],
["重字戴草帽，靠着竖心歇","懂","dǒng","Chữ 重 đội mũ cỏ, dựa vào bộ tâm đứng","艹 + 重 + 忄 → 懂 (hiểu)","忄 · 艹 · 重",3,"dg"],
["小耳朵，总听课，你就聪明了","聪","cōng","Tai nhỏ, luôn (总) nghe giảng, thế là thông minh","耳 + 总 → 聪 (聪明)","耳 · 总",3,"dg"],
["两人站着用尺量，都是一尺一寸长","待","dài","Hai người đứng đo bằng thước, đều dài một thước một tấc","彳 (hai người) + 土 (十 + 一) + 寸 → 待 (等待)","彳 · 土 · 寸",3,"dg"],
["有个孩子叫白方，站在水边看文章","激","jī","Có đứa trẻ tên 白方, đứng bên nước đọc văn","氵 + 白 + 方 + 攵 (文) → 激 (激动)","氵 · 白 · 方 · 攵",3,"dg"],
["一排小朋友，个个背着手，一排变两排，看看没有手","非","fēi","Một hàng bạn nhỏ chắp tay sau lưng; một hàng thành hai hàng, nhìn chẳng thấy tay","Hai hàng nét ngang đứng đối xứng hai bên → 非 (非常)","丨 · 三 · 丨 · 三",3,"dg"],
["一点一横长，一撇到左方，一人中间站，喜事大声讲","庆","qìng","Một chấm, một nét ngang dài, một nét phẩy sang trái, một người đứng giữa; có tin vui thì nói to","广 + 大 → 庆 (庆祝, 国庆)","广 · 大",3,"dg"],
["一个小锅炒豆豆，三颗豆，两颗掉外边，一颗留中间","心","xīn","Chảo nhỏ rang đậu, ba hạt: hai hạt rơi ra ngoài, một hạt ở giữa","Nét cong (cái chảo) + ba chấm (hạt đậu) → 心 (tim)","乚 · 丶 · 丶 · 丶",3,"dg"],
["一飘三点雨，宝盖来顶起，朋友躲下面，爱字记心里","爱","ài","Ba chấm mưa bay, có mái che lên, bạn bè (友) nấp ở dưới","爫 (ba chấm) + 冖 + 友 → 爱 (yêu)","爫 · 冖 · 友",3,"dg"],
["休要丢人现眼","相","xiāng","Chữ 休 bỏ người (亻), thêm con mắt (目)","休 − 亻 = 木, thêm 目 → 相","木 · 目",3,"dg"],
["有耳就能听话","门","mén","Có tai là nghe được lời","门 + 耳 → 闻 (nghe), nên đáp án là 门 (cửa)","门 · 耳",3,"dg"],
["自小在一起，目前少联系","省","shěng","Từ nhỏ ở bên nhau; giờ ít (少) gặp mặt (目)","少 + 目 → 省 (tỉnh)","少 · 目",3,"dg"],
["方院里，小儿睡，数一数，共两对","四","sì","Trong sân vuông có đứa trẻ ngủ; đếm thử, được hai đôi","囗 + 儿 → 四; hai đôi = 4","囗 · 儿",3,"dg"]
];
// Số nét của chữ đáp án (gợi ý ✍️), đếm từ dữ liệu nét chữ HanziWriter / Make Me a Hanzi. Thêm câu đố mới thì thêm số nét ở đây.
window.SO_NET={"朋":8,"吕":6,"品":9,"晶":12,"从":4,"众":6,"林":8,"森":12,"明":8,"卡":5,"国":8,"问":6,"闻":9,"间":7,"回":6,"好":6,"合":6,"休":6,"出":5,"困":7,"王":4,"告":7,"拿":10,"思":9,"坐":7,"茶":9,"胖":9,"生":5,"克":7,"臭":10,"一":1,"肉":6,"重":9,"李":7,"信":9,"哭":10,"闪":5,"吉":6,"朝":12,"米":6,"名":6,"立":5,"默":16,"料":10,"舌":6,"田":5,"目":5,"秋":9,"也":3,"高":10,"金":8,"日":4,"鲜":14,"雷":13,"春":9,"雪":11,"四":5,"根":10,"喜":12,"选":9,"兵":7,"员":7,"步":7,"破":10,"量":12,"懒":16,"非":8,"相":9,"奶":5,"司":5,"心":4,"念":8,"由":5,"化":4,"全":6,"口":3,"爱":10,"热":10,"息":10,"闭":6,"器":16,"聪":15,"原":10,"个":3,"尖":6,"申":5,"岁":6,"花":7,"多":6,"输":13,"要":9,"会":6,"晒":10,"赞":16,"部":10,"实":8,"街":12,"待":9,"门":3,"甲":5,"庆":6,"激":16,"省":9,"转":8,"天":4,"闹":8,"靠":15,"星":9,"懂":15,"必":5,"甜":11,"斗":4,"土":3,"力":2,"九":2,"言":7,"答":12};
